name: "action-package-audit"
author: "smockle"
description: "Requires 2FA for publishing an npm org’s packages."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "shield"
  color: "blue"
